/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IApi3Pool, IApi3PoolInterface } from "../IApi3Pool";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_block",
        type: "uint256",
      },
    ],
    name: "totalSharesAt",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "userAddress",
        type: "address",
      },
      {
        name: "_block",
        type: "uint256",
      },
    ],
    name: "userVotingPowerAt",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "userAddress",
        type: "address",
      },
    ],
    name: "updateLastProposalTimestamp",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "userAddress",
        type: "address",
      },
    ],
    name: "getUser",
    outputs: [
      {
        name: "unstaked",
        type: "uint256",
      },
      {
        name: "vesting",
        type: "uint256",
      },
      {
        name: "unstakeAmount",
        type: "uint256",
      },
      {
        name: "unstakeShares",
        type: "uint256",
      },
      {
        name: "unstakeScheduledFor",
        type: "uint256",
      },
      {
        name: "lastDelegationUpdateTimestamp",
        type: "uint256",
      },
      {
        name: "lastProposalTimestamp",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isGenesisEpoch",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "EPOCH_LENGTH",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalVotingPowerThreshold",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IApi3Pool__factory {
  static readonly abi = _abi;
  static createInterface(): IApi3PoolInterface {
    return new utils.Interface(_abi) as IApi3PoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IApi3Pool {
    return new Contract(address, _abi, signerOrProvider) as IApi3Pool;
  }
}
