/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface Api3PoolInterface extends ethers.utils.Interface {
  functions: {
    "EPOCH_LENGTH()": FunctionFragment;
    "REWARD_VESTING_PERIOD()": FunctionFragment;
    "agentAppPrimary()": FunctionFragment;
    "agentAppSecondary()": FunctionFragment;
    "api3Token()": FunctionFragment;
    "apr()": FunctionFragment;
    "aprUpdateStep()": FunctionFragment;
    "claimsManagerStatus(address)": FunctionFragment;
    "delegateVotingPower(address)": FunctionFragment;
    "delegatedToUser(address)": FunctionFragment;
    "delegatedToUserAt(address,uint256)": FunctionFragment;
    "deposit(address,uint256,address)": FunctionFragment;
    "depositAndStake(uint256)": FunctionFragment;
    "depositRegular(uint256)": FunctionFragment;
    "depositWithVesting(address,uint256,address,uint256,uint256)": FunctionFragment;
    "epochIndexOfLastReward()": FunctionFragment;
    "epochIndexToReward(uint256)": FunctionFragment;
    "genesisEpoch()": FunctionFragment;
    "getUser(address)": FunctionFragment;
    "isGenesisEpoch()": FunctionFragment;
    "maxApr()": FunctionFragment;
    "minApr()": FunctionFragment;
    "mintReward()": FunctionFragment;
    "payOutClaim(address,uint256)": FunctionFragment;
    "poolShares(uint256)": FunctionFragment;
    "precalculateUserLocked(address,uint256)": FunctionFragment;
    "proposalVotingPowerThreshold()": FunctionFragment;
    "scheduleUnstake(uint256)": FunctionFragment;
    "setAprUpdateStep(uint256)": FunctionFragment;
    "setClaimsManagerStatus(address,bool)": FunctionFragment;
    "setDaoApps(address,address,address,address)": FunctionFragment;
    "setMaxApr(uint256)": FunctionFragment;
    "setMinApr(uint256)": FunctionFragment;
    "setProposalVotingPowerThreshold(uint256)": FunctionFragment;
    "setStakeTarget(uint256)": FunctionFragment;
    "setUnstakeWaitPeriod(uint256)": FunctionFragment;
    "stake(uint256)": FunctionFragment;
    "stakeTarget()": FunctionFragment;
    "timelockManager()": FunctionFragment;
    "totalShares()": FunctionFragment;
    "totalSharesAt(uint256)": FunctionFragment;
    "totalStake()": FunctionFragment;
    "undelegateVotingPower()": FunctionFragment;
    "unstake(address)": FunctionFragment;
    "unstakeAndWithdraw()": FunctionFragment;
    "unstakeWaitPeriod()": FunctionFragment;
    "updateLastProposalTimestamp(address)": FunctionFragment;
    "updateTimelockStatus(address)": FunctionFragment;
    "userDelegate(address)": FunctionFragment;
    "userDelegateAt(address,uint256)": FunctionFragment;
    "userLocked(address)": FunctionFragment;
    "userShares(address)": FunctionFragment;
    "userSharesAt(address,uint256)": FunctionFragment;
    "userStake(address)": FunctionFragment;
    "userToLockedCalculation(address)": FunctionFragment;
    "userToTimelock(address)": FunctionFragment;
    "userVotingPower(address)": FunctionFragment;
    "userVotingPowerAt(address,uint256)": FunctionFragment;
    "users(address)": FunctionFragment;
    "votingAppPrimary()": FunctionFragment;
    "votingAppSecondary()": FunctionFragment;
    "withdrawPrecalculated(uint256)": FunctionFragment;
    "withdrawRegular(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "EPOCH_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_VESTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentAppPrimary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentAppSecondary",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "api3Token", values?: undefined): string;
  encodeFunctionData(functionFragment: "apr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aprUpdateStep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimsManagerStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateVotingPower",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegatedToUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegatedToUserAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRegular",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithVesting",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochIndexOfLastReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochIndexToReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getUser", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isGenesisEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxApr", values?: undefined): string;
  encodeFunctionData(functionFragment: "minApr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payOutClaim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "precalculateUserLocked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVotingPowerThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleUnstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAprUpdateStep",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimsManagerStatus",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoApps",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxApr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinApr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProposalVotingPowerThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeTarget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnstakeWaitPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakeTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timelockManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSharesAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateVotingPower",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unstake", values: [string]): string;
  encodeFunctionData(
    functionFragment: "unstakeAndWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeWaitPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateLastProposalTimestamp",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTimelockStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userDelegate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userDelegateAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "userLocked", values: [string]): string;
  encodeFunctionData(functionFragment: "userShares", values: [string]): string;
  encodeFunctionData(
    functionFragment: "userSharesAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "userStake", values: [string]): string;
  encodeFunctionData(
    functionFragment: "userToLockedCalculation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userToTimelock",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userVotingPower",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userVotingPowerAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [string]): string;
  encodeFunctionData(
    functionFragment: "votingAppPrimary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingAppSecondary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrecalculated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRegular",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "EPOCH_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_VESTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentAppPrimary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentAppSecondary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "api3Token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "apr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aprUpdateStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimsManagerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatedToUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatedToUserAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRegular",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochIndexOfLastReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochIndexToReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isGenesisEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxApr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minApr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintReward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payOutClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "precalculateUserLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalVotingPowerThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAprUpdateStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimsManagerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDaoApps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMaxApr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinApr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProposalVotingPowerThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnstakeWaitPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSharesAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "undelegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeWaitPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLastProposalTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTimelockStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDelegateAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userLocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userSharesAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userToLockedCalculation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVotingPowerAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingAppPrimary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingAppSecondary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrecalculated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRegular",
    data: BytesLike
  ): Result;

  events: {
    "CalculatedUserLocked(address,uint256)": EventFragment;
    "CalculatingUserLocked(address,uint256,uint256)": EventFragment;
    "Delegated(address,address,uint256,uint256)": EventFragment;
    "Deposited(address,uint256,uint256)": EventFragment;
    "DepositedByTimelockManager(address,uint256,uint256)": EventFragment;
    "DepositedVesting(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "MintedReward(uint256,uint256,uint256,uint256)": EventFragment;
    "PaidOutClaim(address,uint256,uint256)": EventFragment;
    "ScheduledUnstake(address,uint256,uint256,uint256,uint256)": EventFragment;
    "SetAprUpdateStep(uint256)": EventFragment;
    "SetClaimsManagerStatus(address,bool)": EventFragment;
    "SetDaoApps(address,address,address,address)": EventFragment;
    "SetMaxApr(uint256)": EventFragment;
    "SetMinApr(uint256)": EventFragment;
    "SetProposalVotingPowerThreshold(uint256)": EventFragment;
    "SetStakeTarget(uint256)": EventFragment;
    "SetUnstakeWaitPeriod(uint256)": EventFragment;
    "Staked(address,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "Undelegated(address,address,uint256,uint256)": EventFragment;
    "Unstaked(address,uint256,uint256,uint256,uint256)": EventFragment;
    "UpdatedDelegation(address,address,bool,uint256,uint256)": EventFragment;
    "UpdatedLastProposalTimestamp(address,uint256,address)": EventFragment;
    "VestedTimelock(address,uint256,uint256)": EventFragment;
    "Withdrawn(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CalculatedUserLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CalculatingUserLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Delegated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositedByTimelockManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositedVesting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintedReward"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaidOutClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScheduledUnstake"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAprUpdateStep"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetClaimsManagerStatus"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDaoApps"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxApr"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMinApr"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SetProposalVotingPowerThreshold"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetStakeTarget"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetUnstakeWaitPeriod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Staked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Undelegated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unstaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedDelegation"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UpdatedLastProposalTimestamp"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VestedTimelock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type CalculatedUserLockedEvent = TypedEvent<
  [string, BigNumber],
  { user: string; amount: BigNumber }
>;

export type CalculatedUserLockedEventFilter = TypedEventFilter<CalculatedUserLockedEvent>;

export type CalculatingUserLockedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; nextIndEpoch: BigNumber; oldestLockedEpoch: BigNumber }
>;

export type CalculatingUserLockedEventFilter = TypedEventFilter<CalculatingUserLockedEvent>;

export type DelegatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    user: string;
    delegate: string;
    shares: BigNumber;
    totalDelegatedTo: BigNumber;
  }
>;

export type DelegatedEventFilter = TypedEventFilter<DelegatedEvent>;

export type DepositedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; amount: BigNumber; userUnstaked: BigNumber }
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export type DepositedByTimelockManagerEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; amount: BigNumber; userUnstaked: BigNumber }
>;

export type DepositedByTimelockManagerEventFilter = TypedEventFilter<DepositedByTimelockManagerEvent>;

export type DepositedVestingEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    user: string;
    amount: BigNumber;
    start: BigNumber;
    end: BigNumber;
    userUnstaked: BigNumber;
    userVesting: BigNumber;
  }
>;

export type DepositedVestingEventFilter = TypedEventFilter<DepositedVestingEvent>;

export type MintedRewardEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  {
    epochIndex: BigNumber;
    amount: BigNumber;
    newApr: BigNumber;
    totalStake: BigNumber;
  }
>;

export type MintedRewardEventFilter = TypedEventFilter<MintedRewardEvent>;

export type PaidOutClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { recipient: string; amount: BigNumber; totalStake: BigNumber }
>;

export type PaidOutClaimEventFilter = TypedEventFilter<PaidOutClaimEvent>;

export type ScheduledUnstakeEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    user: string;
    amount: BigNumber;
    shares: BigNumber;
    scheduledFor: BigNumber;
    userShares: BigNumber;
  }
>;

export type ScheduledUnstakeEventFilter = TypedEventFilter<ScheduledUnstakeEvent>;

export type SetAprUpdateStepEvent = TypedEvent<
  [BigNumber],
  { aprUpdateStep: BigNumber }
>;

export type SetAprUpdateStepEventFilter = TypedEventFilter<SetAprUpdateStepEvent>;

export type SetClaimsManagerStatusEvent = TypedEvent<
  [string, boolean],
  { claimsManager: string; status: boolean }
>;

export type SetClaimsManagerStatusEventFilter = TypedEventFilter<SetClaimsManagerStatusEvent>;

export type SetDaoAppsEvent = TypedEvent<
  [string, string, string, string],
  {
    agentAppPrimary: string;
    agentAppSecondary: string;
    votingAppPrimary: string;
    votingAppSecondary: string;
  }
>;

export type SetDaoAppsEventFilter = TypedEventFilter<SetDaoAppsEvent>;

export type SetMaxAprEvent = TypedEvent<[BigNumber], { maxApr: BigNumber }>;

export type SetMaxAprEventFilter = TypedEventFilter<SetMaxAprEvent>;

export type SetMinAprEvent = TypedEvent<[BigNumber], { minApr: BigNumber }>;

export type SetMinAprEventFilter = TypedEventFilter<SetMinAprEvent>;

export type SetProposalVotingPowerThresholdEvent = TypedEvent<
  [BigNumber],
  { proposalVotingPowerThreshold: BigNumber }
>;

export type SetProposalVotingPowerThresholdEventFilter = TypedEventFilter<SetProposalVotingPowerThresholdEvent>;

export type SetStakeTargetEvent = TypedEvent<
  [BigNumber],
  { stakeTarget: BigNumber }
>;

export type SetStakeTargetEventFilter = TypedEventFilter<SetStakeTargetEvent>;

export type SetUnstakeWaitPeriodEvent = TypedEvent<
  [BigNumber],
  { unstakeWaitPeriod: BigNumber }
>;

export type SetUnstakeWaitPeriodEventFilter = TypedEventFilter<SetUnstakeWaitPeriodEvent>;

export type StakedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    user: string;
    amount: BigNumber;
    mintedShares: BigNumber;
    userUnstaked: BigNumber;
    userShares: BigNumber;
    totalShares: BigNumber;
    totalStake: BigNumber;
  }
>;

export type StakedEventFilter = TypedEventFilter<StakedEvent>;

export type UndelegatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    user: string;
    delegate: string;
    shares: BigNumber;
    totalDelegatedTo: BigNumber;
  }
>;

export type UndelegatedEventFilter = TypedEventFilter<UndelegatedEvent>;

export type UnstakedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    user: string;
    amount: BigNumber;
    userUnstaked: BigNumber;
    totalShares: BigNumber;
    totalStake: BigNumber;
  }
>;

export type UnstakedEventFilter = TypedEventFilter<UnstakedEvent>;

export type UpdatedDelegationEvent = TypedEvent<
  [string, string, boolean, BigNumber, BigNumber],
  {
    user: string;
    delegate: string;
    delta: boolean;
    shares: BigNumber;
    totalDelegatedTo: BigNumber;
  }
>;

export type UpdatedDelegationEventFilter = TypedEventFilter<UpdatedDelegationEvent>;

export type UpdatedLastProposalTimestampEvent = TypedEvent<
  [string, BigNumber, string],
  { user: string; lastProposalTimestamp: BigNumber; votingApp: string }
>;

export type UpdatedLastProposalTimestampEventFilter = TypedEventFilter<UpdatedLastProposalTimestampEvent>;

export type VestedTimelockEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; amount: BigNumber; userVesting: BigNumber }
>;

export type VestedTimelockEventFilter = TypedEventFilter<VestedTimelockEvent>;

export type WithdrawnEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; amount: BigNumber; userUnstaked: BigNumber }
>;

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;

export interface Api3Pool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Api3PoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EPOCH_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    REWARD_VESTING_PERIOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    agentAppPrimary(overrides?: CallOverrides): Promise<[string]>;

    agentAppSecondary(overrides?: CallOverrides): Promise<[string]>;

    api3Token(overrides?: CallOverrides): Promise<[string]>;

    apr(overrides?: CallOverrides): Promise<[BigNumber]>;

    aprUpdateStep(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimsManagerStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    delegateVotingPower(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    delegatedToUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    delegatedToUserAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositAndStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositWithVesting(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      releaseStart: BigNumberish,
      releaseEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    epochIndexOfLastReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochIndexToReward(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber] & {
        atBlock: number;
        amount: BigNumber;
        totalSharesThen: BigNumber;
        totalStakeThen: BigNumber;
      }
    >;

    genesisEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        unstaked: BigNumber;
        vesting: BigNumber;
        unstakeAmount: BigNumber;
        unstakeShares: BigNumber;
        unstakeScheduledFor: BigNumber;
        lastDelegationUpdateTimestamp: BigNumber;
        lastProposalTimestamp: BigNumber;
      }
    >;

    isGenesisEpoch(overrides?: CallOverrides): Promise<[boolean]>;

    maxApr(overrides?: CallOverrides): Promise<[BigNumber]>;

    minApr(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    payOutClaim(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    poolShares(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber] & { fromBlock: number; value: BigNumber }>;

    precalculateUserLocked(
      userAddress: string,
      noEpochsPerIteration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposalVotingPowerThreshold(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    scheduleUnstake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAprUpdateStep(
      _aprUpdateStep: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setClaimsManagerStatus(
      claimsManager: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDaoApps(
      _agentAppPrimary: string,
      _agentAppSecondary: string,
      _votingAppPrimary: string,
      _votingAppSecondary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxApr(
      _maxApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinApr(
      _minApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProposalVotingPowerThreshold(
      _proposalVotingPowerThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStakeTarget(
      _stakeTarget: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUnstakeWaitPeriod(
      _unstakeWaitPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakeTarget(overrides?: CallOverrides): Promise<[BigNumber]>;

    timelockManager(overrides?: CallOverrides): Promise<[string]>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSharesAt(
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalStake(overrides?: CallOverrides): Promise<[BigNumber]>;

    undelegateVotingPower(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstake(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstakeAndWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstakeWaitPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateLastProposalTimestamp(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateTimelockStatus(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userDelegate(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    userDelegateAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    userLocked(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { locked: BigNumber }>;

    userShares(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userSharesAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userStake(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userToLockedCalculation(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        initialIndEpoch: BigNumber;
        nextIndEpoch: BigNumber;
        locked: BigNumber;
      }
    >;

    userToTimelock(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalAmount: BigNumber;
        remainingAmount: BigNumber;
        releaseStart: BigNumber;
        releaseEnd: BigNumber;
      }
    >;

    userVotingPower(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userVotingPowerAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        unstaked: BigNumber;
        vesting: BigNumber;
        unstakeAmount: BigNumber;
        unstakeShares: BigNumber;
        unstakeScheduledFor: BigNumber;
        lastDelegationUpdateTimestamp: BigNumber;
        lastProposalTimestamp: BigNumber;
      }
    >;

    votingAppPrimary(overrides?: CallOverrides): Promise<[string]>;

    votingAppSecondary(overrides?: CallOverrides): Promise<[string]>;

    withdrawPrecalculated(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  EPOCH_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  REWARD_VESTING_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

  agentAppPrimary(overrides?: CallOverrides): Promise<string>;

  agentAppSecondary(overrides?: CallOverrides): Promise<string>;

  api3Token(overrides?: CallOverrides): Promise<string>;

  apr(overrides?: CallOverrides): Promise<BigNumber>;

  aprUpdateStep(overrides?: CallOverrides): Promise<BigNumber>;

  claimsManagerStatus(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  delegateVotingPower(
    delegate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  delegatedToUser(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  delegatedToUserAt(
    userAddress: string,
    _block: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    source: string,
    amount: BigNumberish,
    userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositAndStake(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositRegular(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositWithVesting(
    source: string,
    amount: BigNumberish,
    userAddress: string,
    releaseStart: BigNumberish,
    releaseEnd: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  epochIndexOfLastReward(overrides?: CallOverrides): Promise<BigNumber>;

  epochIndexToReward(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber, BigNumber] & {
      atBlock: number;
      amount: BigNumber;
      totalSharesThen: BigNumber;
      totalStakeThen: BigNumber;
    }
  >;

  genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  getUser(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      unstaked: BigNumber;
      vesting: BigNumber;
      unstakeAmount: BigNumber;
      unstakeShares: BigNumber;
      unstakeScheduledFor: BigNumber;
      lastDelegationUpdateTimestamp: BigNumber;
      lastProposalTimestamp: BigNumber;
    }
  >;

  isGenesisEpoch(overrides?: CallOverrides): Promise<boolean>;

  maxApr(overrides?: CallOverrides): Promise<BigNumber>;

  minApr(overrides?: CallOverrides): Promise<BigNumber>;

  mintReward(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  payOutClaim(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  poolShares(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[number, BigNumber] & { fromBlock: number; value: BigNumber }>;

  precalculateUserLocked(
    userAddress: string,
    noEpochsPerIteration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposalVotingPowerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  scheduleUnstake(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAprUpdateStep(
    _aprUpdateStep: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setClaimsManagerStatus(
    claimsManager: string,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDaoApps(
    _agentAppPrimary: string,
    _agentAppSecondary: string,
    _votingAppPrimary: string,
    _votingAppSecondary: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxApr(
    _maxApr: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinApr(
    _minApr: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProposalVotingPowerThreshold(
    _proposalVotingPowerThreshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStakeTarget(
    _stakeTarget: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUnstakeWaitPeriod(
    _unstakeWaitPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stake(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakeTarget(overrides?: CallOverrides): Promise<BigNumber>;

  timelockManager(overrides?: CallOverrides): Promise<string>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  totalSharesAt(
    _block: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalStake(overrides?: CallOverrides): Promise<BigNumber>;

  undelegateVotingPower(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstake(
    userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstakeAndWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstakeWaitPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  updateLastProposalTimestamp(
    userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateTimelockStatus(
    userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userDelegate(userAddress: string, overrides?: CallOverrides): Promise<string>;

  userDelegateAt(
    userAddress: string,
    _block: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  userLocked(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userShares(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userSharesAt(
    userAddress: string,
    _block: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userStake(userAddress: string, overrides?: CallOverrides): Promise<BigNumber>;

  userToLockedCalculation(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      initialIndEpoch: BigNumber;
      nextIndEpoch: BigNumber;
      locked: BigNumber;
    }
  >;

  userToTimelock(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      totalAmount: BigNumber;
      remainingAmount: BigNumber;
      releaseStart: BigNumber;
      releaseEnd: BigNumber;
    }
  >;

  userVotingPower(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userVotingPowerAt(
    userAddress: string,
    _block: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  users(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      unstaked: BigNumber;
      vesting: BigNumber;
      unstakeAmount: BigNumber;
      unstakeShares: BigNumber;
      unstakeScheduledFor: BigNumber;
      lastDelegationUpdateTimestamp: BigNumber;
      lastProposalTimestamp: BigNumber;
    }
  >;

  votingAppPrimary(overrides?: CallOverrides): Promise<string>;

  votingAppSecondary(overrides?: CallOverrides): Promise<string>;

  withdrawPrecalculated(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawRegular(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    EPOCH_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_VESTING_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    agentAppPrimary(overrides?: CallOverrides): Promise<string>;

    agentAppSecondary(overrides?: CallOverrides): Promise<string>;

    api3Token(overrides?: CallOverrides): Promise<string>;

    apr(overrides?: CallOverrides): Promise<BigNumber>;

    aprUpdateStep(overrides?: CallOverrides): Promise<BigNumber>;

    claimsManagerStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    delegateVotingPower(
      delegate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    delegatedToUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegatedToUserAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositAndStake(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositRegular(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithVesting(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      releaseStart: BigNumberish,
      releaseEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    epochIndexOfLastReward(overrides?: CallOverrides): Promise<BigNumber>;

    epochIndexToReward(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber] & {
        atBlock: number;
        amount: BigNumber;
        totalSharesThen: BigNumber;
        totalStakeThen: BigNumber;
      }
    >;

    genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    getUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        unstaked: BigNumber;
        vesting: BigNumber;
        unstakeAmount: BigNumber;
        unstakeShares: BigNumber;
        unstakeScheduledFor: BigNumber;
        lastDelegationUpdateTimestamp: BigNumber;
        lastProposalTimestamp: BigNumber;
      }
    >;

    isGenesisEpoch(overrides?: CallOverrides): Promise<boolean>;

    maxApr(overrides?: CallOverrides): Promise<BigNumber>;

    minApr(overrides?: CallOverrides): Promise<BigNumber>;

    mintReward(overrides?: CallOverrides): Promise<void>;

    payOutClaim(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    poolShares(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber] & { fromBlock: number; value: BigNumber }>;

    precalculateUserLocked(
      userAddress: string,
      noEpochsPerIteration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proposalVotingPowerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    scheduleUnstake(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setAprUpdateStep(
      _aprUpdateStep: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setClaimsManagerStatus(
      claimsManager: string,
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setDaoApps(
      _agentAppPrimary: string,
      _agentAppSecondary: string,
      _votingAppPrimary: string,
      _votingAppSecondary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxApr(_maxApr: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setMinApr(_minApr: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setProposalVotingPowerThreshold(
      _proposalVotingPowerThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStakeTarget(
      _stakeTarget: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setUnstakeWaitPeriod(
      _unstakeWaitPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stake(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    stakeTarget(overrides?: CallOverrides): Promise<BigNumber>;

    timelockManager(overrides?: CallOverrides): Promise<string>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    totalSharesAt(
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStake(overrides?: CallOverrides): Promise<BigNumber>;

    undelegateVotingPower(overrides?: CallOverrides): Promise<void>;

    unstake(userAddress: string, overrides?: CallOverrides): Promise<BigNumber>;

    unstakeAndWithdraw(overrides?: CallOverrides): Promise<void>;

    unstakeWaitPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    updateLastProposalTimestamp(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTimelockStatus(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userDelegate(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    userDelegateAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    userLocked(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userShares(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userSharesAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userStake(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userToLockedCalculation(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        initialIndEpoch: BigNumber;
        nextIndEpoch: BigNumber;
        locked: BigNumber;
      }
    >;

    userToTimelock(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalAmount: BigNumber;
        remainingAmount: BigNumber;
        releaseStart: BigNumber;
        releaseEnd: BigNumber;
      }
    >;

    userVotingPower(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userVotingPowerAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        unstaked: BigNumber;
        vesting: BigNumber;
        unstakeAmount: BigNumber;
        unstakeShares: BigNumber;
        unstakeScheduledFor: BigNumber;
        lastDelegationUpdateTimestamp: BigNumber;
        lastProposalTimestamp: BigNumber;
      }
    >;

    votingAppPrimary(overrides?: CallOverrides): Promise<string>;

    votingAppSecondary(overrides?: CallOverrides): Promise<string>;

    withdrawPrecalculated(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawRegular(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CalculatedUserLocked(address,uint256)"(
      user?: string | null,
      amount?: null
    ): CalculatedUserLockedEventFilter;
    CalculatedUserLocked(
      user?: string | null,
      amount?: null
    ): CalculatedUserLockedEventFilter;

    "CalculatingUserLocked(address,uint256,uint256)"(
      user?: string | null,
      nextIndEpoch?: null,
      oldestLockedEpoch?: null
    ): CalculatingUserLockedEventFilter;
    CalculatingUserLocked(
      user?: string | null,
      nextIndEpoch?: null,
      oldestLockedEpoch?: null
    ): CalculatingUserLockedEventFilter;

    "Delegated(address,address,uint256,uint256)"(
      user?: string | null,
      delegate?: string | null,
      shares?: null,
      totalDelegatedTo?: null
    ): DelegatedEventFilter;
    Delegated(
      user?: string | null,
      delegate?: string | null,
      shares?: null,
      totalDelegatedTo?: null
    ): DelegatedEventFilter;

    "Deposited(address,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): DepositedEventFilter;
    Deposited(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): DepositedEventFilter;

    "DepositedByTimelockManager(address,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): DepositedByTimelockManagerEventFilter;
    DepositedByTimelockManager(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): DepositedByTimelockManagerEventFilter;

    "DepositedVesting(address,uint256,uint256,uint256,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      start?: null,
      end?: null,
      userUnstaked?: null,
      userVesting?: null
    ): DepositedVestingEventFilter;
    DepositedVesting(
      user?: string | null,
      amount?: null,
      start?: null,
      end?: null,
      userUnstaked?: null,
      userVesting?: null
    ): DepositedVestingEventFilter;

    "MintedReward(uint256,uint256,uint256,uint256)"(
      epochIndex?: BigNumberish | null,
      amount?: null,
      newApr?: null,
      totalStake?: null
    ): MintedRewardEventFilter;
    MintedReward(
      epochIndex?: BigNumberish | null,
      amount?: null,
      newApr?: null,
      totalStake?: null
    ): MintedRewardEventFilter;

    "PaidOutClaim(address,uint256,uint256)"(
      recipient?: string | null,
      amount?: null,
      totalStake?: null
    ): PaidOutClaimEventFilter;
    PaidOutClaim(
      recipient?: string | null,
      amount?: null,
      totalStake?: null
    ): PaidOutClaimEventFilter;

    "ScheduledUnstake(address,uint256,uint256,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      shares?: null,
      scheduledFor?: null,
      userShares?: null
    ): ScheduledUnstakeEventFilter;
    ScheduledUnstake(
      user?: string | null,
      amount?: null,
      shares?: null,
      scheduledFor?: null,
      userShares?: null
    ): ScheduledUnstakeEventFilter;

    "SetAprUpdateStep(uint256)"(
      aprUpdateStep?: null
    ): SetAprUpdateStepEventFilter;
    SetAprUpdateStep(aprUpdateStep?: null): SetAprUpdateStepEventFilter;

    "SetClaimsManagerStatus(address,bool)"(
      claimsManager?: string | null,
      status?: boolean | null
    ): SetClaimsManagerStatusEventFilter;
    SetClaimsManagerStatus(
      claimsManager?: string | null,
      status?: boolean | null
    ): SetClaimsManagerStatusEventFilter;

    "SetDaoApps(address,address,address,address)"(
      agentAppPrimary?: null,
      agentAppSecondary?: null,
      votingAppPrimary?: null,
      votingAppSecondary?: null
    ): SetDaoAppsEventFilter;
    SetDaoApps(
      agentAppPrimary?: null,
      agentAppSecondary?: null,
      votingAppPrimary?: null,
      votingAppSecondary?: null
    ): SetDaoAppsEventFilter;

    "SetMaxApr(uint256)"(maxApr?: null): SetMaxAprEventFilter;
    SetMaxApr(maxApr?: null): SetMaxAprEventFilter;

    "SetMinApr(uint256)"(minApr?: null): SetMinAprEventFilter;
    SetMinApr(minApr?: null): SetMinAprEventFilter;

    "SetProposalVotingPowerThreshold(uint256)"(
      proposalVotingPowerThreshold?: null
    ): SetProposalVotingPowerThresholdEventFilter;
    SetProposalVotingPowerThreshold(
      proposalVotingPowerThreshold?: null
    ): SetProposalVotingPowerThresholdEventFilter;

    "SetStakeTarget(uint256)"(stakeTarget?: null): SetStakeTargetEventFilter;
    SetStakeTarget(stakeTarget?: null): SetStakeTargetEventFilter;

    "SetUnstakeWaitPeriod(uint256)"(
      unstakeWaitPeriod?: null
    ): SetUnstakeWaitPeriodEventFilter;
    SetUnstakeWaitPeriod(
      unstakeWaitPeriod?: null
    ): SetUnstakeWaitPeriodEventFilter;

    "Staked(address,uint256,uint256,uint256,uint256,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      mintedShares?: null,
      userUnstaked?: null,
      userShares?: null,
      totalShares?: null,
      totalStake?: null
    ): StakedEventFilter;
    Staked(
      user?: string | null,
      amount?: null,
      mintedShares?: null,
      userUnstaked?: null,
      userShares?: null,
      totalShares?: null,
      totalStake?: null
    ): StakedEventFilter;

    "Undelegated(address,address,uint256,uint256)"(
      user?: string | null,
      delegate?: string | null,
      shares?: null,
      totalDelegatedTo?: null
    ): UndelegatedEventFilter;
    Undelegated(
      user?: string | null,
      delegate?: string | null,
      shares?: null,
      totalDelegatedTo?: null
    ): UndelegatedEventFilter;

    "Unstaked(address,uint256,uint256,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      userUnstaked?: null,
      totalShares?: null,
      totalStake?: null
    ): UnstakedEventFilter;
    Unstaked(
      user?: string | null,
      amount?: null,
      userUnstaked?: null,
      totalShares?: null,
      totalStake?: null
    ): UnstakedEventFilter;

    "UpdatedDelegation(address,address,bool,uint256,uint256)"(
      user?: string | null,
      delegate?: string | null,
      delta?: null,
      shares?: null,
      totalDelegatedTo?: null
    ): UpdatedDelegationEventFilter;
    UpdatedDelegation(
      user?: string | null,
      delegate?: string | null,
      delta?: null,
      shares?: null,
      totalDelegatedTo?: null
    ): UpdatedDelegationEventFilter;

    "UpdatedLastProposalTimestamp(address,uint256,address)"(
      user?: string | null,
      lastProposalTimestamp?: null,
      votingApp?: null
    ): UpdatedLastProposalTimestampEventFilter;
    UpdatedLastProposalTimestamp(
      user?: string | null,
      lastProposalTimestamp?: null,
      votingApp?: null
    ): UpdatedLastProposalTimestampEventFilter;

    "VestedTimelock(address,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      userVesting?: null
    ): VestedTimelockEventFilter;
    VestedTimelock(
      user?: string | null,
      amount?: null,
      userVesting?: null
    ): VestedTimelockEventFilter;

    "Withdrawn(address,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): WithdrawnEventFilter;
    Withdrawn(
      user?: string | null,
      amount?: null,
      userUnstaked?: null
    ): WithdrawnEventFilter;
  };

  estimateGas: {
    EPOCH_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_VESTING_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    agentAppPrimary(overrides?: CallOverrides): Promise<BigNumber>;

    agentAppSecondary(overrides?: CallOverrides): Promise<BigNumber>;

    api3Token(overrides?: CallOverrides): Promise<BigNumber>;

    apr(overrides?: CallOverrides): Promise<BigNumber>;

    aprUpdateStep(overrides?: CallOverrides): Promise<BigNumber>;

    claimsManagerStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegateVotingPower(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    delegatedToUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegatedToUserAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositAndStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositWithVesting(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      releaseStart: BigNumberish,
      releaseEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    epochIndexOfLastReward(overrides?: CallOverrides): Promise<BigNumber>;

    epochIndexToReward(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    getUser(userAddress: string, overrides?: CallOverrides): Promise<BigNumber>;

    isGenesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    maxApr(overrides?: CallOverrides): Promise<BigNumber>;

    minApr(overrides?: CallOverrides): Promise<BigNumber>;

    mintReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    payOutClaim(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    poolShares(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    precalculateUserLocked(
      userAddress: string,
      noEpochsPerIteration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposalVotingPowerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    scheduleUnstake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAprUpdateStep(
      _aprUpdateStep: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setClaimsManagerStatus(
      claimsManager: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDaoApps(
      _agentAppPrimary: string,
      _agentAppSecondary: string,
      _votingAppPrimary: string,
      _votingAppSecondary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxApr(
      _maxApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinApr(
      _minApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProposalVotingPowerThreshold(
      _proposalVotingPowerThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStakeTarget(
      _stakeTarget: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUnstakeWaitPeriod(
      _unstakeWaitPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakeTarget(overrides?: CallOverrides): Promise<BigNumber>;

    timelockManager(overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    totalSharesAt(
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStake(overrides?: CallOverrides): Promise<BigNumber>;

    undelegateVotingPower(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstake(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstakeAndWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstakeWaitPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    updateLastProposalTimestamp(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateTimelockStatus(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userDelegate(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userDelegateAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userLocked(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userShares(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userSharesAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userStake(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userToLockedCalculation(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userToTimelock(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    userVotingPower(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userVotingPowerAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    users(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    votingAppPrimary(overrides?: CallOverrides): Promise<BigNumber>;

    votingAppSecondary(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawPrecalculated(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EPOCH_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REWARD_VESTING_PERIOD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    agentAppPrimary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    agentAppSecondary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    api3Token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    apr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aprUpdateStep(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimsManagerStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegateVotingPower(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    delegatedToUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegatedToUserAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositAndStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositWithVesting(
      source: string,
      amount: BigNumberish,
      userAddress: string,
      releaseStart: BigNumberish,
      releaseEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    epochIndexOfLastReward(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    epochIndexToReward(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genesisEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUser(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isGenesisEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxApr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minApr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    payOutClaim(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    poolShares(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    precalculateUserLocked(
      userAddress: string,
      noEpochsPerIteration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposalVotingPowerThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    scheduleUnstake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAprUpdateStep(
      _aprUpdateStep: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setClaimsManagerStatus(
      claimsManager: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDaoApps(
      _agentAppPrimary: string,
      _agentAppSecondary: string,
      _votingAppPrimary: string,
      _votingAppSecondary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxApr(
      _maxApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinApr(
      _minApr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProposalVotingPowerThreshold(
      _proposalVotingPowerThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStakeTarget(
      _stakeTarget: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUnstakeWaitPeriod(
      _unstakeWaitPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakeTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timelockManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSharesAt(
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalStake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    undelegateVotingPower(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstake(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstakeAndWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstakeWaitPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateLastProposalTimestamp(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateTimelockStatus(
      userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userDelegate(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userDelegateAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userLocked(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userShares(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userSharesAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userStake(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userToLockedCalculation(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userToTimelock(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userVotingPower(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userVotingPowerAt(
      userAddress: string,
      _block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingAppPrimary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votingAppSecondary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawPrecalculated(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawRegular(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
